# Generated by Django 2.2.6 on 2020-01-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200105_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='exit'),
            preserve_default=False,
        ),
    ]
